apiVersion: v1
kind: Secret
metadata:
  name: auto-import-secret
  namespace: ${CLUSTER_NAME}
stringData:
  autoImportRetry: "5"
  # If you are using the kubeconfig file, add the following value for the kubeconfig file
  # that has the current context set to the cluster to import:
  kubeconfig: >- 
    ${KUBECONFIG_B64}
type: Opaque